services:
  api:
    build: .
    environment:
      EVENT_PLATFORM_ENVIRONMENT: local
      EVENT_PLATFORM_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      EVENT_PLATFORM_OTLP_ENDPOINT: http://otel-collector:4318
    ports:
      - "8000:8000"
    depends_on:
      - redpanda
      - postgres
      - redis
      - otel-collector

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 512M
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - ./app/db/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.109.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./deploy/otel/collector.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"

