apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-ingestion-api
  labels:
    app: event-ingestion-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event-ingestion-api
  template:
    metadata:
      labels:
        app: event-ingestion-api
    spec:
      containers:
        - name: api
          image: ghcr.io/uzairkhatri/high-throughput-event-platform/api:latest
          ports:
            - containerPort: 8000
          env:
            - name: EVENT_PLATFORM_ENVIRONMENT
              value: production
            - name: EVENT_PLATFORM_RUNTIME_MODE
              value: distributed
            - name: EVENT_PLATFORM_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: event-platform-secrets
                  key: kafka-bootstrap-servers
            - name: EVENT_PLATFORM_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: event-platform-secrets
                  key: redis-url
            - name: EVENT_PLATFORM_OTLP_ENDPOINT
              value: http://otel-collector:4318
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: event-ingestion-api
spec:
  selector:
    app: event-ingestion-api
  ports:
    - name: http
      port: 80
      targetPort: 8000

